name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.2
    - name: Setup Node
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
