name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.4
    - name: Setup Node
      uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # v2.2.0
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
